project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - text: "Home"
        href: index.qmd
      - text: "Projects"
        href: projects/index.qmd
      - text: "Resume"
        href: projects/resume.qmd
      - text: "About Me"
        href: projects/about.qmd

format:
  html:
    theme: cosmo
    toc: true