project:
  type: website

website:
  title: "My Portfolio"
  navbar:
    left:
      - text: "Home"
        href: projects/index.qmd
      - text: "Projects"
        href: projects/project-demo.qmd
      - text: "SIR Model"
        href: shiny/sir_model/sir.qmd
      - text: "SEIR Model"
        href: shiny/seir_model/seir.qmd
      - text: "Resume"
        href: projects/resume.qmd
      - text: "About Me"
        href: projects/about.qmd

format:
  html:
    theme: cosmo
    toc: true